# Generated by Django 3.0.3 on 2020-03-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20200316_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=1, max_length=50, verbose_name='作者'),
            preserve_default=False,
        ),
    ]
