# Generated by Django 3.0.5 on 2020-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='at_article',
            field=models.CharField(default='none', max_length=50, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='none', max_length=50, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='words',
            field=models.CharField(default='none', max_length=50, verbose_name='文本'),
        ),
    ]
