# Generated by Django 3.0.5 on 2020-07-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_auto_20200706_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
