# Generated by Django 3.0.5 on 2020-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_auto_20200706_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='at_article',
            field=models.CharField(default='none', max_length=50, verbose_name='id'),
        ),
    ]
