# Generated by Django 3.0.8 on 2020-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_auto_20200706_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='look_number',
            field=models.IntegerField(default=0),
        ),
    ]
