# Generated by Django 3.0.5 on 2020-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0019_auto_20200729_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='none', max_length=50, verbose_name='文本'),
        ),
    ]
