# Generated by Django 3.0.5 on 2020-08-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0022_auto_20200806_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo_list',
            field=models.TextField(blank=True, default='none', null=True),
        ),
    ]
