# Generated by Django 3.0.5 on 2020-08-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0023_article_photo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='作者邮箱'),
        ),
    ]
